version: '3'
services:
  mongo:
    container_name: mongo-db
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./.data-volume:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      # - ./mongod.conf:/etc/mongo/mongod.conf
